### ISSUE TITLE
Plans too large

### ISSUE THREAD

**Issue by phangor** [space10-community/the-growroom#12]
The only company I found that can do this for me says that the .dxf plans are too large for their software.  They have asked me for files for each of the 12 sheets individually.  Is this possible or available?

**Comment by danielfriis** [comment]
Hi @Machinistnc - Should be fixed with most recent update. Let me know if it doesn't work for you.

**Comment by danielfriis** [comment]
Hi @phangor  - Should be fixed with most recent update. Let me know if it doesn't work for you.
