### ISSUE TITLE
Good Day! We are unable to download DXF files from the website. I would love to build this project with my Arcitecture and Construction students.

### ISSUE THREAD

**Issue by jronstadt** [space10-community/the-growroom#14]

**Comment by GuilloOme** [comment]
as @danielfriis says here: #2 

> On this page: https://github.com/space10-community/the-growroom
> ... there's a green "Clone or download" button in the top right. Use that to download a zip of the project.

**Comment by GuilloOme** [comment]
On the first page of project, under the section "[Download](https://github.com/space10-community/the-growroom#download)", there is a link for downloading all the files in a .zip

**Comment by danielfriis** [comment]
@jronstadt Closing this one. Let me know if couldn't figure out the download. Also, would love to see the final result when you're done! :)
