### ISSUE TITLE
AutoCAD drawings or scaled blueprints request

### ISSUE THREAD

**Issue by Alounder** [space10-community/the-growroom#16]
Hi,
I'm a carpentry student and would like to build this project with AutoCAD or complete scaled blueprint drawings.
Have these been created? If so, please attach them to the other open source documents.

~A

**Comment by HusumLindholm** [comment]
Hi Alouder.
The drawings have been updated, and you can now find a zip file containing each nested sheet as well as a single file containing all the sheets. All files are .dwg.

Best regards
Husum&Lindholm
