### ISSUE TITLE
Solutions on resizing scaling etc..

### ISSUE THREAD

**Issue by Machinistnc** [space10-community/the-growroom#17]
Hi,
I just got done cutting and assembling TheGrowroom, in the US. Same issues as some have posted.

Wrong size or file too big.
I selected each rectangle and my cad program allows me to enter 96" and 48" that scaled the panel and every shape within with a margin of error of 0.062" in 8 feet.  My program allows me to save a selection as a single drawing. I wind up with 12 dxf drawings in us dimensions

Missing part. One of the parts on the layer that requires 5 curved puzzle parts is not on a panel. When I opened the .dxf drawings in the software for tootpaths I can center vectors in material, and I cut a lot of the wedges and moved them to other panels,spread them out among the other parts, this freed up space on one sheet of plywood to add the missing part and to recut any parts that didn't turn out well.

This reduced my sheets required to12.  I used a 1/4 inch solid carbide uncut spiral bit after some sanding all the parts fit

**Comment by danielfriis** [comment]
Hi @Machinistnc - Should be fixed with most recent update. Let me know if it doesn't work for you.
