### ISSUE TITLE
How do I download the DXF file?

### ISSUE THREAD

**Issue by bigjohn2016** [space10-community/the-growroom#2]
Hell

Great idea and design but, I can't download the DXF file. When I click the download button, it just opens the file in the browser, it doesn't download.

Your help would be appreciated.

Regards - John

**Comment by danielfriis** [comment]
Hi John,

Thanks for your interest!

On this page: https://github.com/space10-community/the-growroom
... there's a green "Clone or download" button in the top right. Use that to download a zip of the project.

Bests,
Daniel

**Comment by bigjohn2016** [comment]
Hello Daniel

That’s perfect, I have it all now, thank you.

My Son showed me this and I instantly thought – half size as a herb garden for the kids, partly because my AXYZ MIllenium CNC machine only has a 1m square bed.

Thanks again for both the help and the data

Kind regards - John
