### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by SimonMcN** [space10-community/the-growroom#4]
The self assembly is good with the mallet and interlocking but it's useless unless the side walls are integrated in to the tool less construction. 
It also gives no details on how it it waterproof. When working with soil this is vital as is having something to catch the excess water. 
A reasonable idea if not viable Imo.

**Comment by danielfriis** [comment]
Hi Simon. Thanks a lot for your input. The Growroom is open source and you are very welcome to experiment with optimising and adjusting as you like. If you do so please share and it may be useful to others.

We are looking into optimising the watering bit and hope to soon release our recommendations on it.
