### ISSUE TITLE
Resizing 

### ISSUE THREAD

**Issue by Shoota75** [space10-community/the-growroom#7]
The drawings don't open and can't be resized so kinda useless for someone who wants to make it smaller but lacks the dfx skills to resize it in code would be nice in a svg file.

**Comment by HusumLindholm** [comment]
Hi Shoota75,

The drawings have now been updated, and you can find a package consisting of each sheet laid out in single files as well as a file consisting of all the sheets. The format is .dwg, and you should be able to convert this to .svg in case you are still interested in building a Growroom.

Best regards
Husum&Lindholm

**Comment by IBKIM01** [comment]
I would like to make smaller size. How can it resize on drawing? I want to make it half size for original.
